a = input('Ho ten: ')
b = int(input('So ngay cong: '))
c = int(input('Don gia ngay cong: '))
d = float(input('He so phu cap: '))
e = int(input('Tam ung: '))
print('Nhan vien ',a, ', Co tien Luong=',c*b*d,', Tam ung=',e,' va Thuc linh=', (c*b*d)-e, sep = '')